backend:
  name: github
  repo: robertowm/robertowm.github.io
  branch: dev
publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Posts"
    folder: "data/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "project"
    label: "Projects"
    folder: "data/projects"
    create: true
    identifier_field: "name"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "project" }
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Short name", name: "short_name", widget: "string", required: true }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Year", name: "year", widget: "date", format: "YYYY" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Me"
        name: "about-me"
        file: "data/content/about-me.md"
        fields:
          - { name: "layout", widget: "hidden", default: "about-me" }
          - { label: "Full Name", name: "full_name", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Profile URL", name: "profile_url", widget: "string" }
          - { label: "CV", name: "cv", widget: "file" }
          - label: "Photo"
            name: "photo"
            widget: "image"
            allow_multiple: "false"
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
      - label: "Qualifications"
        name: "qualifications"
        file: "data/content/qualifications.md"
        fields:
          - { name: "layout", widget: "hidden", default: "qualifications" }
          - label: "Education"
            name: "education"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Institution", name: "institution", widget: "string" }
              - label: "Start Year"
                name: "start_year"
                widget: "date"
                format: "YYYY"
              - label: "End Year"
                name: "end_year"
                widget: "date"
                format: "YYYY"
                default: ""
          - label: "Certifications"
            name: "certifications"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: "Date"
                name: "date"
                widget: "date"
                format: "MMMM YYYY"
              - { label: "URL", name: "url", widget: "string" }
              - label: "Institutions"
                name: "institutions"
                widget: "list"
                field: { label: "Name", name: "name", widget: "string" }
      - label: "Work Experiences"
        name: "work-experiences"
        file: "data/content/work-experiences.md"
        fields:
          - { name: "layout", widget: "hidden", default: "work-experiences" }
          - label: "Work Experience"
            name: "work-experience"
            widget: "list"
            fields:
              - { label: "Company", name: "company", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Position", name: "position", widget: "string" }
              - label: "Start Year"
                name: "start_year"
                widget: "date"
                format: "YYYY"
                required: true
              - label: "End Year"
                name: "end_year"
                widget: "date"
                format: "YYYY"
                default: ""
              - { label: "Summary", name: "summary", widget: "markdown" }